# Generated by Django 5.2.1 on 2025-05-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_createevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createevent',
            name='price',
        ),
        migrations.RemoveField(
            model_name='createevent',
            name='status',
        ),
    ]
