# Generated by Django 5.2.1 on 2025-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_notification_remove_event_date_remove_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createevent',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
